arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n/generated
output-localization-file: app_localizations.dart
synthetic-package: false
no-nullable-getter: true
use-named-parameters: true
